version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 11.0.0.0/24

services:
    #### Monitoring front-end ####
    prometheus:
        build: prometheus/
        image: miratepuffin/raphtory_prometheus:test
        ports:
            - 8888:9090
        volumes:
            - prometheus_data:/prometheus
            - ../Dockerfiles/prometheus/charts_html:/usr/share/prometheus/consoles
        env_file: ../.env
        deploy:
            endpoint_mode: vip
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs
    grafana:
        image: miratepuffin/raphtory_grafana
        user: "472"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./config.monitoring
        deploy:
            endpoint_mode: vip
            replicas: 1

volumes:
    prometheus_data:
    grafana_data: {}
