version: '3.3'


networks:
    default:
        external:
            name: raphtory-prometheus_default

services:
    #### seedSetup ####
    seedNode:
        image: miratepuffin/raphtory:ben
        command: env-setter.sh seedNode
        env_file: .env
        deploy:
            endpoint_mode: dnsrr
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs

    watchDog:
        image: miratepuffin/raphtory:ben
        depends_on:
            - seedNode
        command: env-setter.sh clusterUp
        env_file: .env
        deploy:
            endpoint_mode: vip
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs


    #### Machines Setup ####
    partitionManager:
        image: miratepuffin/raphtory:ben
        depends_on:
            - seedNode
            - watchDog
        command: env-setter.sh partitionManager
        env_file: .env
        deploy:
            endpoint_mode: dnsrr
            #replicas: 1 #$NUMBER_OF_PARTITIONS
            mode: global
            placement:
                constraints:
                    - node.labels.raphtoryrole==partitionManager
  #          resources:
  #              limits:
  #                  memory: 20G
    router:
         image: miratepuffin/raphtory:ben
         depends_on:
            - seedNode
            - watchDog

         command: env-setter.sh router
         env_file: .env
         deploy:
            endpoint_mode: dnsrr
            #replicas: 1
            mode: global
            placement:
                constraints:
                  - node.labels.raphtoryrole==router
#            resources:
#                limits:
#                    cpus: '1'

    updater:
        image: miratepuffin/raphtory:ben
        depends_on:
            - seedNode
            - watchDog
        command: env-setter.sh updater
        env_file: .env
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs
#        volumes:
#            - ./gab:/var/lib/redis
#            - ./redis:/etc/redis


#    lam:
#        image: miratepuffin/raphtory:bazar
#        depends_on:
#            - seedNode
#            - watchDog
#            - partitionManager
#            - router
#        command: env-setter.sh liveAnalysis
#        env_file: .env
#        deploy:
#            endpoint_mode: vip
#            replicas: 1
#            placement:
#                constraints:
#                    - node.labels.raphtoryrole==setupjobs


volumes:
    prometheus_data:
