version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
    #### Monitoring front-end ####
    prometheus:
        build: prometheus/
        image: miratepuffin/raphtory_prometheus
        ports:
            - 8888:9090
        volumes:
            - prometheus_data:/prometheus
            - ./charts_html:/usr/share/prometheus/consoles
        env_file: .env
        deploy:
            endpoint_mode: vip
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==prometheus

    zooKeeper:
         image: miratepuffin/raphtory-zookeeper
         deploy:
             endpoint_mode: vip
             replicas: 1
             placement:
                 constraints:
                    - node.labels.raphtoryrole==setupjobs

    #### seedSetup ####
    seedNode:
        image: miratepuffin/raphtory:ben
        depends_on:
              - zooKeeper
        command: env-setter.sh seedNode
        env_file: .env
        deploy:
            endpoint_mode: dnsrr
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs

    watchDog:
        image: miratepuffin/raphtory:ben
        depends_on:
            - seedNode
            - zooKeeper
        command: env-setter.sh clusterUp
        env_file: .env
        deploy:
            endpoint_mode: vip
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs


    #### Machines Setup ####
    partitionManager:
        image: miratepuffin/raphtory:ben
        depends_on:
            - seedNode
            - watchDog
            - zooKeeper
        command: env-setter.sh partitionManager
        env_file: .env
        deploy:
            endpoint_mode: dnsrr
            #replicas: 1 #$NUMBER_OF_PARTITIONS
            mode: global
            placement:
                constraints:
                    - node.labels.raphtoryrole==mainjob

    router:
         image: miratepuffin/raphtory:ben
         depends_on:
            - zooKeeper
            - seedNode
            - watchDog

         command: env-setter.sh router
         env_file: .env
         deploy:
            endpoint_mode: dnsrr
            #replicas: 1
            mode: global
            placement:
                constraints:
                  - node.labels.raphtoryrole==mainjob
#            resources:
#                limits:
#                    cpus: '1'

    updater:
        image: miratepuffin/raphtory:ben
        depends_on:
            - zooKeeper
            - seedNode
            - watchDog
        command: env-setter.sh updater
        env_file: .env
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs
#        volumes:
#            - ./gab:/var/lib/redis
#            - ./redis:/etc/redis


#    lam:
#        image: miratepuffin/raphtory:bazar
#        depends_on:
#            - seedNode
#            - watchDog
#            - partitionManager
#            - router
#            - zooKeeper
#        command: env-setter.sh liveAnalysis
#        env_file: .env
#        deploy:
#            endpoint_mode: vip
#            replicas: 1
#            placement:
#                constraints:
#                    - node.labels.raphtoryrole==setupjobs


volumes:
    prometheus_data:
