version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 11.0.0.0/24


services:
    #### Monitoring front-end ####
    prometheus:
        image: miratepuffin/raphtory_prometheus:latest
        ports:
            - 8888:9090
        volumes:
            - prometheus_data:/prometheus
            - ../Dockerfiles/prometheus/charts_html:/usr/share/prometheus/consoles
        env_file: .env
        deploy:
            endpoint_mode: vip
            replicas: 1

    grafana:
        image: grafana/grafana
        user: "472"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./config.monitoring
        deploy:
            endpoint_mode: vip
            replicas: 1

    raphtory:
        image: miratepuffin/raphtory:latest
        depends_on:
            - prometheus
        ports:
             - 8080:8080
             - 5266:5266
             - 11600:11600
        command: env-setter.sh singleNodeSetup
        env_file: .env
        volumes:
            - output:/opt/docker

volumes:
    prometheus_data:
    output:
    grafana_data: {}
