version: '3.3'


networks:
    default:
        external:
            name: grafana

services:
    raphtory:
        image: miratepuffin/raphtory:ethereum
        ports:
             - 8080:8080
        command: env-setter.sh singleNodeSetup
        env_file: .env
        volumes:
            - output:/opt/docker
#        deploy:
#            endpoint_mode: dnsrr
#            replicas: 1

volumes:
    output:
