{
 "title": "Raphtory Partition Manager Internals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Available Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Earliest Available Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(sum by(ID,Actor) (Raphtory_Earliest_Time{ID!=\"\"})/2)"
    }
   ]
  },
  {
   "title": "Difference between Safe Time and Latest Update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(min(sum by(ID,Actor) (Raphtory_Latest_Time{ID!=\"\"}))) - (min(sum by(ID,Actor) (Raphtory_Safe_Time{ID!=\"\"})))"
    }
   ]
  },
  {
   "title": "Average time taken for update to appear in watermark",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Raphtory_Wall_Clock_sum[1m])/increase(Raphtory_Wall_Clock_count[1m])/1000"
    }
   ]
  },
  {
   "title": "Latest Safe Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(sum by(ID,Actor) (Raphtory_Safe_Time{ID!=\"\"})/2)"
    }
   ]
  },
  { "title": "Updates and Synchronisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Tuples Incoming From Spout",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ID,Actor)(rate(Raphtory_Spout_Tuples_total[1m])/2)"
    }
   ]
  },
  {
   "title": "Update Output from Routers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(Router,Worker)(rate(Raphtory_Router_Output_total[1m])/2)"
    }
   ]
  },
  {
   "title": "Primary Updates from Routers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ID,Actor)(rate(Raphtory_Router_Updates_total{ID!=\"\"}[1m])/2)"
    }
   ]
  },
  {
   "title": "Internal Synchronisation ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ID,Actor)(rate(Raphtory_Intra_Worker_Updates_total{ID!=\"\"}[1m])/2)"
    }
   ]
  },
  {
   "title": "Unsynchronised Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(ID,Actor)(Raphtory_Router_Updates_total{ID!=\"\"})/2) - (sum by(ID,Actor)(Raphtory_Synchronised_Updates_total{ID!=\"\"})/2) "
    },
    {}
   ]
  },
  {
   "title": "External Synchronisation ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ID,Actor)(rate(Raphtory_Inter_Worker_Updates_total{ID!=\"\"}[1m])/2)"
    }
   ]
  },
  { "title": "Graph Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Number of Vertices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(ID,Actor) (Raphtory_Vertex_Count_total{ID!=\"\"})/2"
    }
   ]
  },
  {
   "title": "Total Edges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(ID,Actor) (Raphtory_Local_Edge_Count_total{ID!=\"\"})/2)+(sum by(ID,Actor) (Raphtory_Master_Split_Edge_Count_total{ID!=\"\"})/2)"
    }
   ]
  },
  {
   "title": "Edge Break Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Local Edge",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(ID,Actor) (Raphtory_Local_Edge_Count_total{ID!=\"\"})/2"
      }
     ]
    },
    {
     "title": "Number of  Master Split Edge",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(ID,Actor) (Raphtory_Master_Split_Edge_Count_total{ID!=\"\"})/2"
      }
     ]
    },
    {
     "title": "Number of  Copy Split Edge",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(ID,Actor) (Raphtory_Copy_Split_Edge_Count_total{ID!=\"\"})/2"
      }
     ]
    }
   ]
  }
 ]
}