version: '3.3'


networks:
    default:
        external:
            name: raphtory-prometheus_default

services:
    lam:
        image: miratepuffin/raphtory:readme
        command: env-setter.sh liveAnalysis
        env_file: ../.env
        volumes:
            - output:/opt/docker
        deploy:
            endpoint_mode: vip
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==setupjobs
            restart_policy:
                condition: on-failure
volumes:
  output:
