version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
    #### Monitoring front-end ####
    prometheus:
        build: prometheus/
        image: miratepuffin/raphtory_prometheus:test
        ports:
            - 8888:9090
        volumes:
            - prometheus_data:/prometheus
            - ../Dockerfiles/prometheus/charts_html:/usr/share/prometheus/consoles
        env_file: ../.env
        deploy:
            endpoint_mode: vip
            replicas: 1
            placement:
                constraints:
                    - node.labels.raphtoryrole==prometheus


volumes:
    prometheus_data:
