{
 "title": "Raphtory Analysis",
 "time": { "from": "2020-06-09T14:33:30.181Z", "to": "2020-06-10T14:33:30.185Z" },
 "panels": [
  {
   "title": "Time taken to complete each view (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (Raphtory_View_Time_Total) by (Timestamp)/1000"
    }
   ]
  },
  {
   "title": "Time taken to concatenate results for view (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (Raphtory_View_Concatenation_Time) by (Timestamp)"
    }
   ]
  },
  {
   "title": "Time taken to build view for superstep (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (Raphtory_View_Build_Time) by (timestamp)/2"
    }
   ]
  },
  {
   "title": "Time taken to build view for superstep (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (Raphtory_Superstep_Time/2) by (timestamp)"
    }
   ]
  },
  {
   "title": "Messages Sent for each view",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (Timestamp) (Raphtory_Analysis_Messages_Sent)/2"
    }
   ]
  }
 ]
}